[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "wodge"
database_id = "f17da2ae-c255-422f-99ad-b8b93733b758"
preview_database_id = "DB"
migrations_dir = "./node_modules/@repo/data/migrations"

