import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@uppy/dashboard/dist/style.min.css";
import "@uppy/core/dist/style.min.css";
import "@uppy/audio/dist/style.min.css";
import "@uppy/webcam/dist/style.min.css";
import "@/styles/uppy.css";
import "@/styles/calls.css";
import "@/styles/editor.css";
import "@/styles/globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import { Providers } from "@/components/providers";
import { Provider } from "jotai";
import { Toaster } from "@/components/ui/toast";
import RoomPage from "./(workspaces)/[workspaceSlug]/(workspace)/room/[teamId]/[channelId]/call/page";
import { AppStoreProvider } from "@/store/app-store-provider";
import { memo } from "react";
import { CallWindow } from "./(workspaces)/[workspaceSlug]/(workspace)/room/[teamId]/[channelId]/call-window";

/** Runtime = edge require in order to make next-auth works with cf-pages */
export const runtime = "edge";

export const metadata: Metadata = {
  title: "Wodge App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body className="relative overflow-hidden font-sans">
        <AppStoreProvider>
          <Provider>
            <Providers>
              <ThemeProvider
                attribute="class"
                defaultTheme="light"
                enableSystem
                disableTransitionOnChange
              >
                {children}
                <CallWindow />
              </ThemeProvider>
            </Providers>
          </Provider>
        </AppStoreProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}

const CallPage = memo(({}) => (
  <div className="absolute right-0 top-0 w-3/4 bg-red-500">
    <RoomPage />
  </div>
));
