import crypto from "node:crypto";

type UniqueKey =
  | "miniflare-KVNamespaceObject"
  | "miniflare-R2BucketObject"
  | "miniflare-D1DatabaseObject"
  | "miniflare-CacheObject";

/**
 * Generates a unique id generated by miniflare for a binding
 * https://github.com/cloudflare/miniflare/releases/tag/v3.20230918.0
 */
export function mfIdFromName(uniqueKey: UniqueKey, binding: string) {
  const key = crypto.createHash("sha256").update(uniqueKey).digest();
  const bindingHmac = crypto
    .createHmac("sha256", key)
    .update(binding)
    .digest()
    .subarray(0, 16);
  const hmac = crypto
    .createHmac("sha256", key)
    .update(bindingHmac)
    .digest()
    .subarray(0, 16);
  return Buffer.concat([bindingHmac, hmac]).toString("hex");
}
