name = "file-system"
compatibility_date = "2023-12-01"

node_compat = true
main = "src/index.ts"
[site]
bucket = "./public"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "test-bucket"
# bucket_name = "test-bucketamx"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
